title: Josh Yamamoto
baseURL: https://example.com
theme: hugo-researcher
disableKinds:
  - taxonomy
  - term
enableEmoji: yes
math: no
googleAnalytics: ''
params:
  author: Olivier Roques
  description: A simple monospaced resume theme for Hugo.
  favicon: favicon.ico
  footer:
    text: By Josh Yamamoto
    url: https://github.com/ojroques/hugo-researcher
permalinks:
  /: /:filename
menu:
  main:
    - name: facts
      url: /facts
      weight: 1
    - name: Blog
      url: /Blog
      weight: 2
markup:
  goldmark:
    renderer:
      unsafe: yes
